version: "3.7"
services:
  rps-services:
    image: rps-services:latest
    build:
      context: .
      target: production
    environment:
      - DB_USER
      - DB_PASSWORD
      - DB_HOST
      - EXPRESS_SESSION_SECRET
      - JWT_SIGNING_SECRET
    depends_on:
      - rps-db
    ports:
      - "8080:8080"
      - "8081:8081"
  rps-db:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    ports:
      - "3306:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - ../data:/var/lib/mysql
  reverse-proxy:
    build: ./reverseProxy
    container_name: reverse-proxy
    ports:
      - "80:80"
      - "443:443"
    expose:
      - "80"
      - "443"
    depends_on:
      - rps-services
    volumes:
      - /var/www/certbot:/var/www/certbot
      - /etc/letsencrypt:/etc/letsencrypt:ro
